<?php


// Devuelve true si hay una nota {muerte} dentro de las notas.
function autoresuy_existeNotamuerte($notasAEvaluar)
{
  $existe = false;

  if (!empty($notasAEvaluar)) {
    foreach ($notasAEvaluar as $cadaNota) {
      $argumento0 = substr ($cadaNota['value'], 1, 6);      
      $eval = ($argumento0 == "muerte");
      $existe = ( $existe || $eval ); } }

  return ($existe);
}

// Devuelve true si hay una nota {estimado} dentro de las notas.
function autoresuy_existeNotaestimado($notasAEvaluar)
{
  $existe = false;

  if (!empty($notasAEvaluar)) {
    foreach ($notasAEvaluar as $cadaNota) {
      $argumento0 = substr ($cadaNota['value'], 1, 8);
      $eval = ( $argumento0 == "estimado" );
      $existe = ( $existe || $eval ); } }

  return ($existe);
}

// Devuelve el año que figura en la nota {muerte}
function autoresuy_evaluarNotamuerte($notasAEvaluar)
{
  foreach ($notasAEvaluar as $cadaNota)
    {
      $argumento0 = substr ($cadaNota['value'], 1, 6);
      
      if ( $argumento0 == "muerte" ) {
        $longitud = strlen ($cadaNota['value'])-5;
        $resultado = substr ($cadaNota['value'], $longitud, 4);
      }
    }

  return ($resultado);
}

// Devuelve el año que figura en la nota {estimado}
function autoresuy_evaluarNotaestimado($notasAEvaluar)
{
  foreach ($notasAEvaluar as $cadaNota)
    {
      $argumento0 = substr ($cadaNota['value'], 1, 8);

      if ($argumento0 == "estimado") {
     
        $longitud = strlen ($cadaNota['value'])-5;
        $resultado = substr ($cadaNota['value'], $longitud, 4);
      }
    }

  return ($resultado);
}


function estatus_derechos_autor ($ano_nacimiento, $ano_muerte, $notas)
{

      $config = \Drupal::service('config.factory')->getEditable('estatus_derechos.settings');

$categoriaDA=13;

$plazoDA = $config->get('plazo_derechos_autor');
$vidaMAX = 100;
$actividad = 20;

$aniodp = date("Y") - $plazoDA;
$anio100 = date("Y") - $vidaMAX;
$anio130 = date("Y") - ($plazoDA + $vidaMAX - $actividad);
$anio150 = date("Y") - ($plazoDA + $vidaMAX);


// Leo campo y dejo solamente el año

  if (!empty($ano_nacimiento)) {
      $anionacimiento = $ano_nacimiento[0]['value'];
  }

  if (!empty($ano_muerte)) {
      $aniomuerte = $ano_muerte[0]['value'];
  }


  if (!empty($ano_muerte)) {
// F. de nacimiento conocida y F. de muerte conocida o F. de nacimiento desconocida y F. de muerte conocida

 if ($aniomuerte < $aniodp) {
    $categoriaDA=0;}
  else {
    $categoriaDA=1;} }

else {
  if (!empty($anionacimiento)) {
    if (!autoresuy_existeNotamuerte($notas)) { // Si no existe Notamuerte (Función que se fija si existe una nota {muerte} y devuelve true si la hay)
    // F. de nacimiento conocida y F. de muerte desconocida sin notas {muerte}
            switch (true) {
                  case ($anionacimiento < $anio150):
                  $categoriaDA=4;
            break;
                  case ($anionacimiento <= $anio100 && $anionacimiento >= $anio150):
                  $categoriaDA=3;
            break;
                  case ($anionacimiento > $anio100):
                  $categoriaDA=2;
            break;  } }
    else { // Si existe Notamuerte
            $notaMuertevalor = autoresuy_evaluarNotamuerte($notas);
            switch (true) {
                  case ($anionacimiento >= $anio100 && $notaMuertevalor >= $aniodp):
                  $categoriaDA=2;
            break;
                  case ($anionacimiento >= $anio100 && $notaMuertevalor < $aniodp):
                  $categoriaDA=6;
            break;
                  case ($anionacimiento < $anio100 && $anionacimiento >= $anio150 && $notaMuertevalor >= $aniodp):
                  $categoriaDA=5;
            break;
                  case ($anionacimiento <= $anio100 && $anionacimiento >= $anio150 && $notaMuertevalor < $aniodp):
                  $categoriaDA=6;
            break;
                  case ($anionacimiento < $anio150):
                  $categoriaDA=4;
            break;  } } }

  else { // F. de nacimiento desconocida y F. de muerte desconocida con nota {estimado}
    if (autoresuy_existeNotaestimado($notas)) { 
            $notaEstimadovalor = autoresuy_evaluarNotaestimado($notas);

            switch (true) {
                  case ($notaEstimadovalor >= $aniodp):
                  $categoriaDA=7;
            break;
                  case ($notaEstimadovalor < $aniodp && $notaEstimadovalor >= $anio130):
                  $categoriaDA=8;
            break;
                  case ($notaEstimadovalor < $anio130):
                  $categoriaDA=9;
            break;  } }

    if (autoresuy_existeNotamuerte($notas)) {
            $notaMuertevalor = autoresuy_evaluarNotamuerte($notas);

            switch (true) {
                  case ($notaMuertevalor >= $aniodp):
                  $categoriaDA=10;
            break;
                  case ($notaMuertevalor < $aniodp):
                  $categoriaDA=11;
            break;  } }

    if ( (!autoresuy_existeNotamuerte($notas)) && (!autoresuy_existeNotaestimado($notas)) ) {
                  $categoriaDA=12; }
  } }

  return $categoriaDA;

}


function estatus_derechos_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {

  if (($entity->getEntityTypeId() == 'node') && ($entity->getType() == 'autor')) {
    $arreglo = $entity->toArray();
    $ano_nacimiento = $arreglo['field_ano_de_nacimiento'];
    $ano_muerte = $arreglo['field_ano_de_muerte'];
    $notas = $arreglo['field_notas'];
    $estatus_derechos_autor = estatus_derechos_autor ($ano_nacimiento, $ano_muerte, $notas);

// Obtengo el tid a partir del codigo de derechos de autor.
    $query = \Drupal::entityQuery('taxonomy_term')
      ->condition('vid', 'estatus_de_derechos')
      ->condition('name', $estatus_derechos_autor);
    $tid = $query->execute();
    $tidcodigo = key($tid);

    $field_estatusderechos = array ();
    array_push($field_estatusderechos, $tidcodigo);

    $entity->set('field_estatusderechos', $field_estatusderechos);
    
    }
    
}

function estatus_derechos_theme($existing, $type, $theme, $path) {

  $arreglo['resultadoModulo'] = NULL;

  return array(
    'vista' => array(
      'variables' => $arreglo,
    ),
  );
}